### ISSUE TITLE
Unable to move certain pieces 2 spaces

### ISSUE THREAD

**Issue by bjvoth** [Team-Divergence/chess#65]
@jackpip, @EmmanuelJucaban, @MarcMcArthur, @janetmohler  I expect to be able to move bishops, rooks, and queens more than one space, as long as it is a valid move. Instead, even when it would be a valid move, I am unable to move those pieces more than one space, regardless of the direction of the move.

To recreate, move the white pawn at x = 1 forward one or two spaces, then try to move the white bishop at x = 2 to the dark square at x = 0, y = 5.

**Comment by OxManny-Dev** [comment]
Yes. I found this bug a couple of days ago. I'm not completely sure what is causing it yet.
